#!/bin/sh
# bbbush <bbbush@163.com> 20031123
# hosiet <073plan@gmail.com> 20161216 (review)

man2html="/usr/bin/groff -T html -m mandoc"
if [ ! $# -le "1" ] ;then
	echo "Error! $0 Need exactly 1 arguments and act as a pipe"
	exit
elif [ $# -eq 1 ] ;then
	$man2html $1 2>/dev/null
else
	$man2html - 2>/dev/null
fi
